In [1]:
import pandas as pd
import numpy as np
from datetime import datetime

In [2]:
import sqlite3

database = 'database.sqlite'

conn = sqlite3.connect(database)

In [3]:
tables = pd.read_sql("""SELECT *
                     FROM sqlite_master
                     WHERE type='table';""", conn)
tables

,type,name,tbl_name,rootpage,sql
0,table,Player,Player,2,CREATE TABLE [Player] (\n\t[Player_Id]\tintege...
1,table,Extra_Runs,Extra_Runs,3,CREATE TABLE [Extra_Runs] (\n\t[Match_Id]\tint...
2,table,Batsman_Scored,Batsman_Scored,7,CREATE TABLE [Batsman_Scored] (\n\t[Match_Id]\...
3,table,Batting_Style,Batting_Style,10,CREATE TABLE [Batting_Style] (\n\t[Batting_Id]...
4,table,Bowling_Style,Bowling_Style,11,CREATE TABLE [Bowling_Style] (\n\t[Bowling_Id]...
5,table,Country,Country,12,CREATE TABLE [Country] (\n\t[Country_Id]\tinte...
6,table,Season,Season,14,CREATE TABLE [Season] (\n\t[Season_Id]\tintege...
7,table,City,City,15,CREATE TABLE [City] (\n\t[City_Id]\tinteger NO...
8,table,Outcome,Outcome,16,CREATE TABLE [Outcome] (\n\t[Outcome_Id]\tinte...
9,table,Win_By,Win_By,17,CREATE TABLE [Win_By] (\n\t[Win_Id]\tinteger N...
10,table,Wicket_Taken,Wicket_Taken,18,CREATE TABLE [Wicket_Taken] (\n\t[Match_Id]\ti...
11,table,Venue,Venue,21,CREATE TABLE [Venue] (\n\t[Venue_Id]\tinteger ...
12,table,Extra_Type,Extra_Type,23,CREATE TABLE [Extra_Type] (\n\t[Extra_Id]\tint...
13,table,Out_Type,Out_Type,24,CREATE TABLE [Out_Type] (\n\t[Out_Id]\tinteger...
14,table,Toss_Decision,Toss_Decision,25,CREATE TABLE [Toss_Decision] (\n\t[Toss_Id]\ti...
15,table,Umpire,Umpire,26,CREATE TABLE [Umpire] (\n\t[Umpire_Id]\tintege...
16,table,Team,Team,27,CREATE TABLE [Team] (\n\t[Team_Id]\tinteger NO...
17,table,Ball_by_Ball,Ball_by_Ball,28,CREATE TABLE [Ball_by_Ball] (\n\t[Match_Id]\ti...
18,table,sysdiagrams,sysdiagrams,31,CREATE TABLE [sysdiagrams] (\n\t[name]\tnvarch...
19,table,sqlite_sequence,sqlite_sequence,32,"CREATE TABLE sqlite_sequence(name,seq)"
20,table,Match,Match,34,CREATE TABLE [Match] (\n\t[Match_Id]\tinteger ...
21,table,Rolee,Rolee,36,CREATE TABLE [Rolee] (\n\t[Role_Id]\tinteger N...
22,table,Player_Match,Player_Match,37,CREATE TABLE [Player_Match] (\n\t[Match_Id]\ti...
23,table,CLASS_10,CLASS_10,3132,CREATE TABLE CLASS_10\n (SNO INT PRIMAR...

In [4]:
match_details = pd.read_sql("""SELECT Season_Id, Match_Id,
                            v.Venue_Name, c.City_Name, t.Team_Name AS Winner
                            FROM Match
                            INNER JOIN Venue AS v ON match.Venue_Id == v.Venue_Id
                            INNER JOIN City AS c ON v.City_Id == c.City_Id
                            INNER JOIN Team AS t ON match.Match_Winner == t.Team_Id;""", conn)

match_details

,Season_Id,Match_Id,Venue_Name,City_Name,Winner
0,1,335987,M Chinnaswamy Stadium,Bangalore,Kolkata Knight Riders
1,1,335988,"Punjab Cricket Association Stadium, Mohali",Chandigarh,Chennai Super Kings
2,1,335989,Feroz Shah Kotla,Delhi,Delhi Daredevils
3,1,335990,Wankhede Stadium,Mumbai,Royal Challengers Bangalore
4,1,335991,Eden Gardens,Kolkata,Kolkata Knight Riders
...,...,...,...,...,...
569,9,981016,Shaheed Veer Narayan Singh International Stadium,Raipur,Royal Challengers Bangalore
570,9,981018,M Chinnaswamy Stadium,Bangalore,Royal Challengers Bangalore
571,9,981020,Feroz Shah Kotla,Delhi,Sunrisers Hyderabad
572,9,981022,Feroz Shah Kotla,Delhi,Sunrisers Hyderabad
573,9,981024,M Chinnaswamy Stadium,Bangalore,Sunrisers Hyderabad