In [2]:
import sqlite3

conn =  sqlite3.connect('database.sqlite')

print("Opened database successfully")

Opened database successfully

In [3]:
conn.execute('''CREATE TABLE CLASS_10
        (SNO INT PRIMARY KEY NOT NULL,
        Roll_No INT NOT NULL,
        Name TEXT NOT NULL,
        AGE INT DEFAULT (15),
        GENDER TEXT NOT NULL,
        Email_ID TEXT NOT NULL,
        Contact_No REAL NOT NULL);''')

print("Table created successfully")

Table created successfully

In [4]:
conn.execute("INSERT INTO CLASS_10 (SNO,Roll_No,NAME,AGE,Gender,Email_ID,Contact_No) \
        VALUES (1, 1, 'Allen', 14, 'Male', 'allen@gmail.com', 8080900)");

conn.execute("INSERT INTO CLASS_10 (SNO,Roll_No,NAME,AGE,Gender,Email_ID,Contact_No) \
        VALUES (2, 2, 'Alisha', 14, 'Female', 'alisha@gmail.com', 8080901)");

conn.execute("INSERT INTO CLASS_10 (SNO,Roll_No,NAME,AGE,Gender,Email_ID,Contact_No) \
        VALUES (3, 3, 'Jef', 15, 'Male', 'jef@gmail.com', 8080902)");

conn.commit()
print("Records created successfully")

Records created successfully

In [6]:
import pandas as pd
tables = pd.read_sql("""SELECT *
                     FROM sqlite_master
                     WHERE type='table';""", conn)
tables

,type,name,tbl_name,rootpage,sql
0,table,Player,Player,2,CREATE TABLE [Player] (\n\t[Player_Id]\tintege...
1,table,Extra_Runs,Extra_Runs,3,CREATE TABLE [Extra_Runs] (\n\t[Match_Id]\tint...
2,table,Batsman_Scored,Batsman_Scored,7,CREATE TABLE [Batsman_Scored] (\n\t[Match_Id]\...
3,table,Batting_Style,Batting_Style,10,CREATE TABLE [Batting_Style] (\n\t[Batting_Id]...
4,table,Bowling_Style,Bowling_Style,11,CREATE TABLE [Bowling_Style] (\n\t[Bowling_Id]...
5,table,Country,Country,12,CREATE TABLE [Country] (\n\t[Country_Id]\tinte...
6,table,Season,Season,14,CREATE TABLE [Season] (\n\t[Season_Id]\tintege...
7,table,City,City,15,CREATE TABLE [City] (\n\t[City_Id]\tinteger NO...
8,table,Outcome,Outcome,16,CREATE TABLE [Outcome] (\n\t[Outcome_Id]\tinte...
9,table,Win_By,Win_By,17,CREATE TABLE [Win_By] (\n\t[Win_Id]\tinteger N...
10,table,Wicket_Taken,Wicket_Taken,18,CREATE TABLE [Wicket_Taken] (\n\t[Match_Id]\ti...
11,table,Venue,Venue,21,CREATE TABLE [Venue] (\n\t[Venue_Id]\tinteger ...
12,table,Extra_Type,Extra_Type,23,CREATE TABLE [Extra_Type] (\n\t[Extra_Id]\tint...
13,table,Out_Type,Out_Type,24,CREATE TABLE [Out_Type] (\n\t[Out_Id]\tinteger...
14,table,Toss_Decision,Toss_Decision,25,CREATE TABLE [Toss_Decision] (\n\t[Toss_Id]\ti...
15,table,Umpire,Umpire,26,CREATE TABLE [Umpire] (\n\t[Umpire_Id]\tintege...
16,table,Team,Team,27,CREATE TABLE [Team] (\n\t[Team_Id]\tinteger NO...
17,table,Ball_by_Ball,Ball_by_Ball,28,CREATE TABLE [Ball_by_Ball] (\n\t[Match_Id]\ti...
18,table,sysdiagrams,sysdiagrams,31,CREATE TABLE [sysdiagrams] (\n\t[name]\tnvarch...
19,table,sqlite_sequence,sqlite_sequence,32,"CREATE TABLE sqlite_sequence(name,seq)"
20,table,Match,Match,34,CREATE TABLE [Match] (\n\t[Match_Id]\tinteger ...
21,table,Rolee,Rolee,36,CREATE TABLE [Rolee] (\n\t[Role_Id]\tinteger N...
22,table,Player_Match,Player_Match,37,CREATE TABLE [Player_Match] (\n\t[Match_Id]\ti...
23,table,CLASS_10,CLASS_10,3132,CREATE TABLE CLASS_10\n (SNO INT PRIMAR...

In [7]:
class_10d = pd.read_sql("""SELECT *
                        FROm CLASS_10;""", conn)

class_10d.head()

   SNO  Roll_No    Name  AGE  GENDER          Email_ID  Contact_No
0    1        1   Allen   14    Male   allen@gmail.com   8080900.0
1    2        2  Alisha   14  Female  alisha@gmail.com   8080901.0
2    3        3     Jef   15    Male     jef@gmail.com   8080902.0