In [1]:
import pandas as pd
import numpy as np

In [2]:
import sqlite3
database = 'database.sqlite'
conn = sqlite3.connect(database)

In [3]:
tables = pd.read_sql("""SELECT *
                     FROM sqlite_master
                     WHERE type='table';""", conn)
tables

,type,name,tbl_name,rootpage,sql
0,table,Player,Player,2,CREATE TABLE [Player] (\n\t[Player_Id]\tintege...
1,table,Extra_Runs,Extra_Runs,3,CREATE TABLE [Extra_Runs] (\n\t[Match_Id]\tint...
2,table,Batsman_Scored,Batsman_Scored,7,CREATE TABLE [Batsman_Scored] (\n\t[Match_Id]\...
3,table,Batting_Style,Batting_Style,10,CREATE TABLE [Batting_Style] (\n\t[Batting_Id]...
4,table,Bowling_Style,Bowling_Style,11,CREATE TABLE [Bowling_Style] (\n\t[Bowling_Id]...
5,table,Country,Country,12,CREATE TABLE [Country] (\n\t[Country_Id]\tinte...
6,table,Season,Season,14,CREATE TABLE [Season] (\n\t[Season_Id]\tintege...
7,table,City,City,15,CREATE TABLE [City] (\n\t[City_Id]\tinteger NO...
8,table,Outcome,Outcome,16,CREATE TABLE [Outcome] (\n\t[Outcome_Id]\tinte...
9,table,Win_By,Win_By,17,CREATE TABLE [Win_By] (\n\t[Win_Id]\tinteger N...
10,table,Wicket_Taken,Wicket_Taken,18,CREATE TABLE [Wicket_Taken] (\n\t[Match_Id]\ti...
11,table,Venue,Venue,21,CREATE TABLE [Venue] (\n\t[Venue_Id]\tinteger ...
12,table,Extra_Type,Extra_Type,23,CREATE TABLE [Extra_Type] (\n\t[Extra_Id]\tint...
13,table,Out_Type,Out_Type,24,CREATE TABLE [Out_Type] (\n\t[Out_Id]\tinteger...
14,table,Toss_Decision,Toss_Decision,25,CREATE TABLE [Toss_Decision] (\n\t[Toss_Id]\ti...
15,table,Umpire,Umpire,26,CREATE TABLE [Umpire] (\n\t[Umpire_Id]\tintege...
16,table,Team,Team,27,CREATE TABLE [Team] (\n\t[Team_Id]\tinteger NO...
17,table,Ball_by_Ball,Ball_by_Ball,28,CREATE TABLE [Ball_by_Ball] (\n\t[Match_Id]\ti...
18,table,sysdiagrams,sysdiagrams,31,CREATE TABLE [sysdiagrams] (\n\t[name]\tnvarch...
19,table,sqlite_sequence,sqlite_sequence,32,"CREATE TABLE sqlite_sequence(name,seq)"
20,table,Match,Match,34,CREATE TABLE [Match] (\n\t[Match_Id]\tinteger ...
21,table,Rolee,Rolee,36,CREATE TABLE [Rolee] (\n\t[Role_Id]\tinteger N...
22,table,Player_Match,Player_Match,37,CREATE TABLE [Player_Match] (\n\t[Match_Id]\ti...
23,table,CLASS_10,CLASS_10,3132,CREATE TABLE CLASS_10\n (SNO INT PRIMAR...

In [4]:
team = pd.read_sql("""SELECT * FROM Team""", conn)

team

    Team_Id                    Team_Name
0         1        Kolkata Knight Riders
1         2  Royal Challengers Bangalore
2         3          Chennai Super Kings
3         4              Kings XI Punjab
4         5             Rajasthan Royals
5         6             Delhi Daredevils
6         7               Mumbai Indians
7         8              Deccan Chargers
8         9         Kochi Tuskers Kerala
9        10                Pune Warriors
10       11          Sunrisers Hyderabad
11       12      Rising Pune Supergiants
12       13                Gujarat Lions

In [6]:
season = pd.read_sql(""" SELECT * FROM Season""", conn)

season

   Season_Id  Man_of_the_Series  Orange_Cap  Purple_Cap  Season_Year
0          1                 32         100         102         2008
1          2                 53          18          61         2009
2          3                133         133         131         2010
3          4                162         162         194         2011
4          5                315         162         190         2012
5          6                 32          19          71         2013
6          7                305          46         364         2014
7          8                334         187          71         2015
8          9                  8           8         299         2016

In [8]:
csk_matches_2015 = pd.read_sql("""SELECT Match_Id, Team_2 as Away_Team, Toss_Winner, Match_Winner
                              FROM Match
                              WHERE Team_1 =
                              (SeLECT Team_1
                              FROM Match
                              WHERE Team_1 == 3 AND Season_Id == 8)""", conn)

print("Matches played By Chennai super Kings in Year 2015")

csk_matches_2015

Matches played By Chennai super Kings in Year 2015

    Match_Id  Away_Team  Toss_Winner  Match_Winner
0     335994          7            7             3
1     335998          1            1             3
2     336006          6            3             6
3     336012          8            8             8
4     336018          4            4             3
..       ...        ...          ...           ...
69    829784          2            3             3
70    829794          7            3             7
71    829802          5            3             3
72    829822          7            7             7
73    829826          2            3             3

[74 rows x 4 columns]

In [10]:
csk_wins = pd.read_sql("""SELECT *
                      FROM Match
                      WHERE Match_Winner == 3 AND Season_Id == 8""", conn)

print("Match won by CSK as Home Team in Year 2015")
csk_wins

Match won by CSK as Home Team in Year 2015

,Match_Id,Team_1,Team_2,Match_Date,Season_Id,Venue_Id,Toss_Winner,Toss_Decide,Win_Type,Win_Margin,Outcome_type,Match_Winner,Man_of_the_Match
0,829712,3,6,2015-04-09 00:00:00,8,8,6,1,1,1,1,3,73
1,829716,3,11,2015-04-11 00:00:00,8,8,3,2,1,45,1,3,2
2,829734,7,3,2015-04-17 00:00:00,8,4,7,2,2,6,1,3,73
3,829750,2,3,2015-04-22 00:00:00,8,1,2,1,1,27,1,3,21
4,829758,3,4,2015-04-25 00:00:00,8,8,3,2,1,97,1,3,2
5,829770,3,1,2015-04-28 00:00:00,8,8,1,1,1,2,1,3,71
6,829784,3,2,2015-05-04 00:00:00,8,8,3,2,1,24,1,3,21
7,829802,3,5,2015-05-10 00:00:00,8,8,3,2,1,12,1,3,35
8,829814,4,3,2015-05-16 00:00:00,8,2,4,2,2,7,1,3,322
9,829826,3,2,2015-05-22 00:00:00,8,28,3,1,2,3,1,3,73

In [12]:
match_runs = pd.read_sql("""SELECT Match_Id, Runs_Scored as Total_Runs, Innings_No
                        FROM Batsman_Scored
                        WHERE Total_Runs > 5 AND Match_Id IN
                        (SELECT Match_Id
                        FROM Match
                        WHERE Season_Id == 8)""", conn)

print("Matches with Scopred Runs Greater than 5 in Year 2015")
match_runs

Matches with Scopred Runs Greater than 5 in Year 2015

     Match_Id  Total_Runs  Innings_No
0      829710           6           2
1      829710           6           2
2      829710           6           1
3      829710           6           2
4      829710           6           2
..        ...         ...         ...
687    829828           6           1
688    829828           6           1
689    829828           6           2
690    829828           6           1
691    829828           6           2

[692 rows x 3 columns]

In [14]:
avg_runs = pd.read_sql("""SELECT Match_Id, Runs_Scored as Total_Runs, Innings_No
                       FROM Batsman_Scored
                       WHERE Innings_No == 1 AND Runs_Scored >
                       (SELECT AVG(Runs_Scored)
                       FROM Batsman_Scored)""", conn)
print("Matches with scored Runs greater than Average Runs Scored")
avg_runs

Matches with scored Runs greater than Average Runs Scored

       Match_Id  Total_Runs  Innings_No
0        335987           4           1
1        335987           4           1
2        335987           6           1
3        335987           4           1
4        335987           4           1
...         ...         ...         ...
16049    981024           4           1
16050    981024           4           1
16051    981024           6           1
16052    981024           6           1
16053    981024           6           1

[16054 rows x 3 columns]